### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nharrand** [Digyanoen/VandV#10]
- [x] Le projet se lance depuis un terminal
- [x] Le projet implémente 4 opérateurs
- [x] Les tests couvrent bien le package processors mais mal le package Testing et la classe Main
- [x] Pas encore de rapport
- [x] Extensions (Travis, +1 opérateur, html report)

(Ce feedback ne prends pas en compte les commits à partir de 27355e36d397b862feb434a90b3b4c03c907e7eb )

**Comment by NFortun** [comment]
Concernant les tests j'aurai une question. Vu que le main est simplement le lancement de l'application, devons-nous le tester ? De plus pour le package Testing, ce sont essentiellement des fonctions Spoon. Devons nous quand même vérifier leur fonctionnement ? De plus ces méthodes s'appuyent pour beaucoup de fichiers générés, alors, à moins de mocker de nombreux appels de fonctions, les tests vont s'avérer difficile.

Enfin, qu'entendez vous par les extensions ? Car à ma connaissance, nous avons fait plus que le minimum requis. Nous avons plus de mutants que le minimum, nous avons mis en place une intégration continue (travis) et nous générons un rapport à la fin de l’exécution du programme.

**Comment by nharrand** [comment]
A propos des tests, j'entends bien que ces packages ne représentent pas le cœur de votre outil. Cela dit, il est important de vérifier au moins à gros grain que leur comportement est bien celui désiré. Même lorsque vous ne faites que wrapper des appels vers une autre bibliothèque des erreurs peuvent arriver (comportement inattendu de la bibliothèque, mauvaise compréhension de son fonctionnement, et dans le cadre d'un développement continu cela aide à mettre à jour les bibliothèque). 

Pour les extensions, autant pour moi, travis, un opérateur et le rapport ça compte. Par contre si vous pouviez le mentionner dans le readme, ça m'éviterai de passer à coté.

Si vous corrigez #9, ça va commencer à être pas mal.

**Comment by NFortun** [comment]
Monsieur, j'aimerais savoir s'il est utile et nécessaire de tester la class Result. En effet, cette classe génère simplement un rapport. Alors, à moins de vérifier que pour un mutant donnée, elle affiche les bonnes valeurs, je ne vois pas quoi faire. Et je ne trouve pas ça très pertinent de tester cette classe. Qu'en pensez-vous ?

**Comment by NFortun** [comment]
De plus, la classe TestUnitHandler contient quasiment que des méthodes privées. D'après ce que j'ai pu lire sur internet, les méthodes privées ne se testent pas. Quant à la méthode getFailures, je n'arrive pas à tester la boucle, du au fait que des nombreux appels de méthodes. Auriez-vous quelque chose à me conseiller ?
