### ISSUE TITLE
Inclure hide.js dans les ressources et le packager avec le rapport généré

### ISSUE THREAD

**Issue by nharrand** [Digyanoen/VandV#11]
Lorsque l'on appel l'outil depuis un répertoire quelconque autre que la racine, le rapport est généré mais l'inclusion de hide.js est brisée.

**Comment by NFortun** [comment]
Qu'est ce que vous entendez par le packager ? De plus comment faites-vous pour lancer le programme en ligne de commande ? Je n'y arrive pas

**Comment by nharrand** [comment]
Pour lancer le programme en CLI:
```
java -jar path/to/jar-with-dependancies.jar args...
```
Pour packger le script avec le jar, il suffit de le déplacer dans `src/main/resources`, maven le mettra dans le jar.

Pour y acceder depuis java:
```java
        ClassLoader classLoader = getClass().getClassLoader();
        File script = new File(classLoader.getResource("hide.js").getFile());
```
A partir de là, il faut soit le copier dans le repertoire dans lequel le rapport sera généré, soit en copier le contenu et l'insérer dans le html entre des balises `<script></script>`.

**Comment by NFortun** [comment]
C'est étrange, car lorsque je fais un java -jar, j'obtiens une exception, que je n'ai pas lorsque je le lance avaec intellij

**Comment by nharrand** [comment]
Laquelle?

**Comment by NFortun** [comment]
C'est un ClassNotFoundException avec le projet commons-cli

**Comment by nharrand** [comment]
Il faut probablement ajouter le jar de commons-cli (si c'est une classe de commons-cli) au classpath avec l'option -cp, mais si d'autre class provenant des dépendances commons-cli, il y a plusieurs solutions:
- lancer le programme via maven (pour bénéficier du classpath géré par maven), 
- soit si le problème survient au lancement des tests du projet cible (si ils sont lancés directement avec le runner de junit) bidouiller le classpath programatiquement avant de les lancer. (Ou encore abandonner le runner junit et lancer les tests via l'api de maven)

**Comment by nharrand** [comment]
C'est une classe de commons-cli qui manque?

**Comment by NFortun** [comment]
Oui, c'est une classe de commons-cli. Je testerai ces différentes solutions durant le weekend. Merci !

**Comment by NFortun** [comment]
Le problème est réglé. L'ajout de -cp à la commande java permet de lancer le projet en ligne de commande. Cependant, il met beaucoup plus de temps qu'avec un IDE
