### ISSUE TITLE
Le readme suggère de lancer le projet via un IDE.

### ISSUE THREAD

**Issue by nharrand** [Digyanoen/VandV#4]
Votre projet peux tout à fait être lancé sans. 
Un IDE ne peux pas être l’environnement d’exécution par défaut.

Un jar avec dépendances devrait être ajouter à la liste des choses à construire par Maven.

**Comment by NFortun** [comment]
Fait

**Comment by nharrand** [comment]
Puisque le problème est réglé, le readme pourrait être modifié en conséquence.
