### ISSUE TITLE
La détéction des tests s'appuie implicitement sur l'annotation @Test

### ISSUE THREAD

**Issue by nharrand** [Digyanoen/VandV#9]
Il faut au moins le préciser dans le readme car cela signifie que votre projet ne support pas Junit3 qui au lieu d'être annotée @Test, étendent la classe TestCase.

Il vous est aussi possible de permettre à l'utilisateur de lister les classes de testes lui même, soit dans un fichier property, soit via un pattern (ex org.mydomain.mypackage.*Test ).

**Comment by Digyanoen** [comment]
C'était le cas quand on essayait d'utiliser le compilateur de Spoon, ce qui nous demandais de charger les fichiers de tests. Maintenant nous nous basons sur la structure d'un projet Maven séparant d'un côté les sources et de l'autre les tests, donc nous n'avons plus besoin de filtrer.
